### ISSUE TITLE
rename properly

### ISSUE THREAD

**Issue by blshkv** [strayge/pylnk#1]
Hi, there are 2 issues with the current release.
The first one, pypi package (https://files.pythonhosted.org/packages/d0/44/ed8fe42645e44b12f4a1771927c661965a606eb71f4fbc57bdcbd3d7e867/pylnk3-0.2.1.tar.gz) is broken due to missing README.md. 

The second one is with the package name. setup.py installs all files into ```..../site-packages/pylnk3-0.2.1-py3.6.egg-info```, however the main python file is still called "pylnk.py".
Either rename egg file back to pylnk or the main file to "pylnk3.py".

Thank you

**Comment by strayge** [comment]
@blshkv, thank for report!
Now looks like fixed, but feel free to reopen if I still missed something.
