### ISSUE TITLE
local path issues

### ISSUE THREAD

**Issue by micprz** [strayge/pylnk#10]
Hello,

I have found 2 minor issues. Note that I have found bypasses for them, so they don't block me, but they may be bugs.

1. I create a LNK to folder on Desktop, by RMB-drag. Then I copied LNK somewhere else, to make sure it will still point to right place. When I read it I get:

```
lnk = pylnk3.Lnk('c:\\Users\\user\\test_lnk.lnk')			
>>> lnk.path
'New folder'
>>> lnk.relative_path
'.\\New folder'
>>> lnk.link_info.path
'C:\\Users\\user\\Desktop\\New folder'
```

I would expect lnk.path to be correct, but I had to use lnk.link_info.path instead. After peeking into code, seems related to _shell_item_id_list.

2. One of my shortcuts on Desktop contains '%MY_COMPUTER%\' prefix, I had to remove it manually so the path makes sense. I don't have such env var in my environment.

```
>>> lnk3.path
'%MY_COMPUTER%\\C:\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Resolve.exe'
>>> lnk3.relative_path
'..\\..\\..\\Program Files\\Blackmagic Design\\DaVinci Resolve\\Resolve.exe'
>>> lnk3.link_info.path
>>>
```

So now I have such bypass:
lnk_target = lnk.link_info.path
if not lnk_target:
    lnk_target = lnk.path.replace ('%MY_COMPUTER%\\', '')

**Comment by micprz** [comment]
BTW. There is also one property named working_dir, which is never used, I think work_dir is the proper one, so this one should be removed (line 1609).

**Comment by strayge** [comment]
thanks for feedback

> I have found 2 minor issues.

fixed in [master branch](https://github.com/strayge/pylnk/commit/55b0f2c40a607d13d8bc7338952a6a83600da7d1)

> There is also one property named working_dir, which is never used

it's alias (legacy from original python2 library).  
i prefer to keep it (until it no cost to maintenance) as someone may use it.

**Comment by strayge** [comment]
feel free to reopen if i miss something
