### ISSUE TITLE
Split API into a separate module and document

### ISSUE THREAD

**Issue by lordmauve** [strayge/pylnk#16]
I believe pylnk is intended to be used as a library, but it is a single-file that includes the CLI code. I cannot see any documentation for the API.

I would like to be able to:

* Create links using an API
* Read documentation for that API
* Not pay the cost of importing argparse, which will not be used.

Some context: I would like to use pylnk in a piece of software that is packaged using PyInstaller. Because PyInstaller produces a package with an executable file (myapp.exe), it is much harder to arrange to include a pylnk3 excutable (pylnk3.exe) and to run it, than it is to just import a module and call it.

**Comment by strayge** [comment]
## Split project to modules

### Why it's not done yet:

1. It broke back compatibility.
2. It mostly useful for developing, not for using. And there is no active developing.
3. It's required some time which I do not have for this project.

### Topic points

#### 1. Create links using an API

Splitting only gain visibility of private & public parts.  
Considering documented functions as public will lead to the same result with much less work.

#### 2. Not pay the cost of importing argparse, which will not be used.

Can be fixed just by moving `argparse` import into `cli` function, no actual modules needed.

#### 3. It is much harder to arrange to include a pylnk3 excutable (pylnk3.exe) and to run it, than it is to just import a module and call it

You definitely can import `pylnk3.py` and use it as module, not only as cli tool.

## Document API

It definitely can be done without any obvious caveats.

I'm open for PRs =)

**Comment by strayge** [comment]
split to modules done in dev branch
documentation not included, but examples can be seen in cli module
