### ISSUE TITLE
How to change path?

### ISSUE THREAD

**Issue by JakobDev** [strayge/pylnk#17]
I need to change the path of a desktop link, because to the program has been moved. How can I do that? I tried to set the path attribute, but it gives me an error:
```python
link = pylnk3.Lnk(link_path)
link.path = new_path
# AttributeError: can't set attribute 'path'
```

**Comment by strayge** [comment]
Probably best way is create new shortcut file:

```python3
from pylnk3 import parse, for_file
lnk = parse('1.lnk')
for_file(
    target_file=lnk.path,
    lnk_name='2.lnk',
    arguments=lnk.arguments,
    description=lnk.description,
    work_dir=lnk.work_dir,
    window_mode=lnk.window_mode,
    icon_file=lnk.icon,
    icon_index=lnk.icon_index,
)
```

**Comment by JakobDev** [comment]
Thanks

**Comment by andry81** [comment]
> I need to change the path of a desktop link, because to the program has been moved. How can I do that? I tried to set the path attribute, but it gives me an error:
> 
> ```python
> link = pylnk3.Lnk(link_path)
> link.path = new_path
> # AttributeError: can't set attribute 'path'
> ```

You can just try to print all attributes: `link.__dict__`
