### ISSUE TITLE
PyLnk3 is incompatible with Python 3.5 (and, as a result, Ubuntu 16.04 LTS)

### ISSUE THREAD

**Issue by ssokolow** [strayge/pylnk#2]
Currently, I have to keep some code on systems running Ubuntu 16.04 LTS on Python 2, because Ubuntu 16.04 comes with Python 3.5.2, but PyLnk3 uses type annotations that the parser doesn't understand until a more recent version of Python. (3.7, I think, but don't quote me on that)

The result is this:

```
$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylnk3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pylnk3.py", line 378
    self._flags: Dict[str, bool] = dict([(name, False) for name in flag_names])
               ^
SyntaxError: invalid syntax
```

The solution is to change to a type comment in those situations

```python
self._flags = dict([(name, False) for name in flag_names])  # type: Dict[str, bool]
```

**Comment by strayge** [comment]
Yes, variable annotations supports only with python 3.6.
But I don't like to remove it only for 3.5 support.
Also python 3.5 end of life is 2020-09-13 and Ubuntu 20.04.1 release in 2 weeks.
