### ISSUE TITLE
Generated LNK not working on Windows when using script API

### ISSUE THREAD

**Issue by HuskyHacks** [strayge/pylnk#22]
Hello,

I'm using pylnk3 to create a test LNK file that opens cmd.exe to spawn notepad.exe for security research. I'm using it in a script that I'm running on Linux, if that makes a difference.

My code in the script is the following:

```python3
from pylnk3 import parse, for_file

...

def make_lnk():
    lnk = for_file(
        target_file = "C:\\Windows\\System32\\cmd.exe",
        lnk_name='tmp.lnk',
        arguments="/c C:\Windows\System32\\notepad.exe",
        description="test",
        work_dir="C:\Windows\System32",
        window_mode="Minimized",
        icon_file="C:\Windows\System32\\notepad.exe",
        icon_index=0,
    )
    print("\n" + str(lnk))

    lnk.save("tmp.lnk")

    # For troubleshooting...
    parse_out = parse("tmp.lnk")

    print('\n' + str(parse_out))

```
The lnk that this produces does not run on Windows. It looks like the Target attribute is not set in the lnk:

![image](https://user-images.githubusercontent.com/57866415/186452971-015ddb39-656a-4235-8644-9e1383b1f6ae.png)

Though what's interesting to note is that other properties, like the Comment, Start In, and Window fields look good.

Am I missing something?

For reference, here's the output of the print statements:

```
Target file:
{ 'archive': False,
  'compressed': False,
  'directory': False,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2022-08-24 10:55:18.671077
Modification Time: 2022-08-24 10:55:18.671080
Access Time: 2022-08-24 10:55:18.671079
File size: 0
Window mode: Minimized
Hotkey: None
None
<LinkTargetIDList>:
  <RootEntry: MY_COMPUTER>
  <DriveEntry: b'C:'>
  <PathSegmentEntry: Windows>
  <PathSegmentEntry: System32>
  <PathSegmentEntry: cmd.exe>
Description: test
Working Directory: C:\Windows\System32
Commandline Arguments: /c C:\Windows\System32\notepad.exe
Icon: C:\Windows\System32\notepad.exe
```

```
Target file:
{ 'archive': False,
  'compressed': False,
  'directory': False,
  'encrypted': False,
  'hidden': False,
  'normal': False,
  'not_content_indexed': False,
  'offline': False,
  'read_only': False,
  'reparse_point': False,
  'reserved1': False,
  'reserved2': False,
  'sparse_file': False,
  'system_file': False,
  'temporary': False}
Creation Time: 2022-08-24 10:55:18
Modification Time: 2022-08-24 10:55:18
Access Time: 2022-08-24 10:55:18
File size: 0
Window mode: Minimized
Hotkey: 
File Location Info: <not specified>
<LinkTargetIDList>:
  <RootEntry: MY_COMPUTER>
  <DriveEntry: b'C:'>
  <PathSegmentEntry: Windows>
  <PathSegmentEntry: System32>
  <PathSegmentEntry: cmd.exe>
Description: test
Working Directory: C:\Windows\System32
Commandline Arguments: /c C:\Windows\System32\notepad.exe
Icon: C:\Windows\System32\notepad.exe
Used Path: C:\Windows\System32\cmd.exe
```

**Comment by HuskyHacks** [comment]
I kinda figured it out. This will work on Windows if you run it from Windows. It does not write to the LNK attributes correctly if you "cross-compile" it from Linux.

**Comment by v-p-b** [comment]
Can you provide some more info about what breaks on Linux? 

Also, this should be considered for reopening, `setup.py` states this is an OS independent lib.

**Comment by v-p-b** [comment]
As you can see I figured it out. The problem is not Windows, but the fact, that cmd.exe (from the original example) doesn't exist on Linux. I think my PR resolves this, and maybe you can also workaround the problem by creating dummy files locally.

**Comment by XP1** [comment]
I had the same problem on Linux. The `target_file` is a Windows path, which doesn't exist on Linux.

Updated to [pylnk3 1.0.0a1](https://github.com/strayge/pylnk/tree/dev) from https://github.com/strayge/pylnk/pull/24#issuecomment-1345678732. This works:

```
pip install "pylnk3>=1.0.0a1"
```

```
import pylnk3.helpers

pylnk3.helpers.for_file(target_path, lnk_name=lnk_path, icon_file=target_path, is_file=True)
```
