### ISSUE TITLE
Links are not builded correctly on linux

### ISSUE THREAD

**Issue by p-real96** [strayge/pylnk#23]
If I run the following command on a linux system:
```

pylnk3 c C:\Windows\notepad.exe notepad.lnk
```
.. and transfer it on a windows host, the LNK file seems to be corrupt, because the slashes were removed:

<img width="356" alt="lnk_file" src="https://user-images.githubusercontent.com/72663672/194105763-cde13f67-cb20-4ab5-a946-54dd5a536dbd.png">

Does the link creation only works on windows or is there any other solution?

Thanks a lot!

**Comment by v-p-b** [comment]
You should escape backslashes or use single quotes in your command line...

**Comment by strayge** [comment]
there are actually 2 different problems:
1. backslashes should be escaped in bash on linux
2. pylnk was set wrong target type for non-existed locally targets, which is fixed in `1.0.0a1`
