### ISSUE TITLE
Add support for pathlib's Path()

### ISSUE THREAD

**Issue by Bexa2** [strayge/pylnk#26]
https://docs.python.org/3/library/pathlib.html

I don't think you'd have to deal with stuff like `.replace('\\\\', '\\')`

**Comment by strayge** [comment]
Hi, thanks for suggestion.

It can be way to go, but

1. Most complex logic around backslashes now is parsing network paths and `PureWindowsPath` works not very well with them:
```python
In [17]: p = PureWindowsPath('\\\\127.0.0.1\\share_name\\path\\name.mkv')

In [18]: p.parts
Out[18]: ('\\\\127.0.0.1\\share_name\\', 'path', 'name.mkv')

In [19]: p.drive
Out[19]: '\\\\127.0.0.1\\share_name'
```

2. We still need strings to convert it to bytes, so it will be `str -> PureWindowsPath -> str -> bytes` conversion.

So, at the end I don't see big profit from that change, and I'm not completely convinced it simplify code or increase readability.

But you can try make some changes, create PR and we discuss simplicity / readability.
