### ISSUE TITLE
pylnk3 not working in python3.7.7

### ISSUE THREAD

**Issue by DreamoryIndia** [strayge/pylnk#3]
While parsing link file using 'parse' argument the following error occured:

ValueError: month must be in 1..12

**Comment by strayge** [comment]
Hi,
Thanks for feedback.
Unfortunately, lnk files can be very different. They depends on file type, windows version, etc.

I just tested with random link, and parsing works on python 3.7.7:
```sh
$ python --version
Python 3.7.7

$ python ./pylnk3.py p 1.lnk
...
Creation Time: 2018-12-15 01:15:32.940672
Modification Time: 2012-11-16 07:34:22
Access Time: 2020-07-24 20:21:48.696865
...
```

So it link specific problem.
If you can share problem lnk file I can try to dig up a bit more.

**Comment by DreamoryIndia** [comment]
Hey,
You are right, I tried with different link file. It worked.
Thanks for your reply.
