### ISSUE TITLE
Making links for files with emojis in their name doesn't seem to work

### ISSUE THREAD

**Issue by FloPinguin** [strayge/pylnk#33]
The following simple code results in an unusable .lnk file:

_import pylnk3
shortcut = pylnk3.for_file("C:/Users/Flo/Desktop/💚 hello.txt")
shortcut.save("C:/Users/Flo/Desktop/test.lnk")_

**Comment by strayge** [comment]
should be fixed in dev branch

**Comment by FloPinguin** [comment]
Sorry, can you tell me how to install / build the package from the dev branch? There is no pylnk3.py there
